In [10]:
import pandas as pd
import numpy as np

In [11]:
#para cargar un archivo
df=pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")
dataframe=pd.read_csv("../data/raw/annual-population-growth/annual-population-growth.csv")

#Exploración 
#df.head()            primeras filas
#df.shape             dimensioes
#df.columns.tolist()  nombres de columnas

In [12]:
df.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN
3,Afghanistan,AFG,1954,111251.0,NaN
4,Afghanistan,AFG,1955,119027.0,NaN

In [13]:
df.shape

(38400, 5)

In [14]:
# el .tolist hace que te de la información en una lista
df.columns.tolist()

['Entity',
 'Code',
 'Year',
 'Annual change in population',
 'Annual population change (Projected)']

In [15]:
df.dtypes

Entity                                   object
Code                                     object
Year                                      int64
Annual change in population             float64
Annual population change (Projected)    float64
dtype: object

In [16]:
df.describe()

,Year,Annual change in population,Annual population change (Projected)
count,38400.000000,1.868800e+04,1.971200e+04
mean,2025.500000,2.063019e+06,8.375481e+05
std,43.300872,9.440859e+06,5.816745e+06
min,1951.000000,-3.315935e+06,-2.291035e+07
25%,1988.000000,1.781000e+03,-9.742750e+03
50%,2025.500000,4.689800e+04,9.350000e+01
75%,2063.000000,3.021128e+05,1.411160e+05
max,2100.000000,9.337137e+07,7.206736e+07

In [17]:
# Me va a defir cuantos datos nulos hay
df.isnull().sum()

Entity                                      0
Code                                     1200
Year                                        0
Annual change in population             19712
Annual population change (Projected)    18688
dtype: int64

In [18]:
df["Entity"].nunique()

256

In [ ]:
df.head(3)

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
0,Afghanistan,AFG,1951,103163.0,NaN
1,Afghanistan,AFG,1952,108441.0,NaN
2,Afghanistan,AFG,1953,108919.0,NaN

In [20]:
df["Year"]

0        1951
1        1952
2        1953
3        1954
4        1955
         ...
38395    2096
38396    2097
38397    2098
38398    2099
38399    2100
Name: Year, Length: 38400, dtype: int64

In [21]:
df_year=df["Year"]
df_year.head()

0    1951
1    1952
2    1953
3    1954
4    1955
Name: Year, dtype: int64

In [ ]:
df_year=df[["Year"]]
df_year.head()

   Year
0  1951
1  1952
2  1953
3  1954
4  1955

In [23]:
df_extraccion_filas = df[df["Year"]== 2020]
df_extraccion_filas.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
69,Afghanistan,AFG,2020,1212852.0,NaN
219,Africa (UN),UN_AFR,2020,32815675.0,NaN
369,Albania,ALB,2020,-13061.0,NaN
519,Algeria,DZA,2020,747543.0,NaN
669,American Samoa,ASM,2020,-451.0,NaN

In [24]:
df_2020_mx = df[(df["Year"]==2020) & (df["Entity"]=="Mexico")]
df_2020_mx.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22269,Mexico,MEX,2020,1036075.0,NaN

In [26]:
#Rango de fechas desdeñaño que nacimos hasta el 2020
df_2005_2020_mex = df [(df["Year"] >= 2005) & (df["Year"] <= 2020) & (df["Code"] == "MEX")]
df_2005_2020_mex.head()

,Entity,Code,Year,Annual change in population,Annual population change (Projected)
22254,Mexico,MEX,2005,1417373.0,NaN
22255,Mexico,MEX,2006,1442162.0,NaN
22256,Mexico,MEX,2007,1520690.0,NaN
22257,Mexico,MEX,2008,1599930.0,NaN
22258,Mexico,MEX,2009,1625434.0,NaN

In [33]:
#Rango de fechas desdeñaño que nacimos hasta el 2020
df_extraccion_rango_mex_EYA=df_2005_2020_mex [["Entity","Year","Annual change in population"]]
df_extraccion_rango_mex_EYA

       Entity  Year  Annual change in population
22254  Mexico  2005                    1417373.0
22255  Mexico  2006                    1442162.0
22256  Mexico  2007                    1520690.0
22257  Mexico  2008                    1599930.0
22258  Mexico  2009                    1625434.0
22259  Mexico  2010                    1624178.0
22260  Mexico  2011                    1619605.0
22261  Mexico  2012                    1574705.0
22262  Mexico  2013                    1525364.0
22263  Mexico  2014                    1440693.0
22264  Mexico  2015                    1288045.0
22265  Mexico  2016                    1179034.0
22266  Mexico  2017                    1148708.0
22267  Mexico  2018                    1173661.0
22268  Mexico  2019                    1189265.0
22269  Mexico  2020                    1036075.0

In [ ]:
df_new=df["Entity"]

NameError: name 'df' is not defined